/**
 * Frontend-only Gemini AI advisory service.
 * Used as a fallback when the backend server is unreachable.
 * Calls the Google Gemini REST API directly using the Expo env var.
 */

const GEMINI_API_KEY =
    process.env.EXPO_PUBLIC_GOOGLE_GENAI_API_KEY || '';

const GEMINI_URL =
    'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent';

const SYSTEM_PROMPT = `You are AgriSarathi, an expert Indian agricultural AI assistant.
Rules:
- Reply in the SAME language the farmer uses (Hindi → Hindi, English → English, Telugu → Telugu, etc.).
- Keep your answer concise: 3-5 sentences max.
- Always give specific, actionable advice (product name, dosage, timing).
- If unsure, say so and suggest consulting a local KVK (Krishi Vigyan Kendra).
- Be warm and respectful — address the farmer politely.`;

export interface GeminiAdviceResult {
    advice: string;
    id: string;
    confidence: number;
    reasoning: string;
}

/**
 * Get agricultural advice directly from Gemini API.
 * @param text  The farmer's question / voice transcription
 * @param context  Optional context (crop, location, language, etc.)
 */
export async function getGeminiAdvice(
    text: string,
    context: Record<string, any> = {},
): Promise<GeminiAdviceResult> {
    if (!GEMINI_API_KEY) {
        return {
            advice:
                'Gemini API key not configured. Please add EXPO_PUBLIC_GOOGLE_GENAI_API_KEY to your .env file.',
            id: 'err_no_key',
            confidence: 0,
            reasoning: 'Missing API key',
        };
    }

    const contextStr = Object.entries(context)
        .filter(([, v]) => v)
        .map(([k, v]) => `${k}: ${v}`)
        .join(', ');

    const userPrompt = contextStr
        ? `Farmer context — ${contextStr}\n\nQuestion: ${text}`
        : text;

    try {
        const res = await fetch(`${GEMINI_URL}?key=${GEMINI_API_KEY}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                system_instruction: { parts: [{ text: SYSTEM_PROMPT }] },
                contents: [{ parts: [{ text: userPrompt }] }],
                generationConfig: {
                    temperature: 0.7,
                    maxOutputTokens: 300,
                },
            }),
        });

        if (!res.ok) {
            const errBody = await res.text();
            console.error('[GeminiAdvice] API error:', res.status, errBody);
            throw new Error(`Gemini API returned ${res.status}`);
        }

        const data = await res.json();
        const answer =
            data?.candidates?.[0]?.content?.parts?.[0]?.text ||
            'Sorry, I could not generate advice at this time.';

        return {
            advice: answer,
            id: `gemini_${Date.now()}`,
            confidence: 0.85,
            reasoning: 'Response generated by Google Gemini (frontend fallback)',
        };
    } catch (err: any) {
        console.error('[GeminiAdvice] Error:', err);
        return {
            advice:
                'I had trouble connecting to the AI service. Please check your internet connection and try again.',
            id: `err_${Date.now()}`,
            confidence: 0,
            reasoning: err.message,
        };
    }
}
