from typing import Dict, Any
from datetime import datetime
import os
import httpx

from app.core.config import settings


GEMINI_API_KEY = settings.GEMINI_API_KEY if settings.GEMINI_API_KEY not in ("placeholder", "") else os.getenv("GEMINI_API_KEY", "")
GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

SYSTEM_PROMPT = """You are AgriSarathi, an expert Indian agricultural AI assistant.
Rules:
- Reply in the SAME language the farmer uses (Hindi → Hindi, English → English, Telugu → Telugu, etc.).
- Keep your answer concise: 3-5 sentences max.
- Always give specific, actionable advice (product name, dosage, timing).
- If unsure, say so and suggest consulting a local KVK (Krishi Vigyan Kendra).
- Be warm and respectful — address the farmer politely.
- Include urgency level in your assessment."""


async def _ask_gemini(prompt: str) -> str | None:
    """Call Gemini REST API and return the text response, or None on failure."""
    if not GEMINI_API_KEY:
        return None
    try:
        async with httpx.AsyncClient(timeout=20) as client:
            resp = await client.post(
                f"{GEMINI_URL}?key={GEMINI_API_KEY}",
                json={
                    "system_instruction": {"parts": [{"text": SYSTEM_PROMPT}]},
                    "contents": [{"parts": [{"text": prompt}]}],
                    "generationConfig": {
                        "temperature": 0.7,
                        "maxOutputTokens": 300,
                    },
                },
            )
            if resp.status_code != 200:
                print(f"[Gemini] API error: {resp.status_code} {resp.text[:200]}")
                return None
            data = resp.json()
            return data.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text")
    except Exception as e:
        print(f"[Gemini] Request failed: {e}")
        return None


class AdvisoryReasoningEngine:
    @staticmethod
    async def get_actionable_advice(query: str, context: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        The heart of Agri: Converts query + context into 'Action-First' advice.
        Tries Google Gemini first, falls back to keyword-based logic.
        """
        from app.services.profile_service import ProfileManager, ContextInjector

        # Get context if not provided
        if not context:
            profile = ProfileManager.get_farmer_context("919876543210")
            weather = {"temp": 32, "condition": "Sunny but Cloudy"}
            market = {"avg_price": "₹25/kg"}
            context = ContextInjector.inject(profile, weather, market)

        # Safety: Ensure context has all required keys
        required_keys = ["farmer_name", "location", "current_season", "weather"]
        for key in required_keys:
            if key not in context:
                context[key] = "Unknown" if key != "farmer_name" else "Farmer"

        query_lower = query.lower()

        # Check for error signals from AIService
        if "[error:" in query_lower:
            target_lang = context.get('language', 'en')
            return {
                "id": f"err_{datetime.now().strftime('%Y%m%d%H%M%S')}",
                "advice": "I couldn't process your voice. Please try again or type your question.",
                "confidence": 0.0,
                "reasoning": "Voice transcription failed.",
                "urgency": "Low",
                "timestamp": datetime.now().isoformat()
            }

        # ------------------------------------------------------------------
        # STEP 1: Try Gemini for intelligent advice
        # ------------------------------------------------------------------
        context_str = ", ".join(f"{k}: {v}" for k, v in context.items() if v and k != "farmer_name")
        farmer_name = context.get("farmer_name", "Farmer")
        gemini_prompt = (
            f"Farmer name: {farmer_name}\n"
            f"Context: {context_str}\n\n"
            f"Question: {query}"
        )

        gemini_answer = await _ask_gemini(gemini_prompt)

        if gemini_answer:
            # Determine urgency from keywords
            is_pest = any(w in query_lower for w in ["pest", "bug", "insect", "yellow", "spot", "worm", "curling", "disease"])
            return {
                "id": f"adv_{datetime.now().strftime('%Y%m%d%H%M%S')}",
                "advice": gemini_answer,
                "confidence": 0.88,
                "reasoning": "Response generated by Google Gemini AI.",
                "urgency": "High" if is_pest else "Medium",
                "timestamp": datetime.now().isoformat()
            }

        # ------------------------------------------------------------------
        # STEP 2: Fallback — keyword-based pattern matching (original logic)
        # ------------------------------------------------------------------
        print("[Advisory] Gemini unavailable, using keyword fallback.")

        is_pest = any(word in query_lower for word in ["curling", "pest", "bug", "insect", "yellow", "spot", "worm", "aphid"])
        is_irrigation = any(word in query_lower for word in ["water", "dry", "irrigation", "motor", "pump", "moisture", "rain"])
        is_fertilizer = any(word in query_lower for word in ["fertilizer", "urea", "potash", "growth", "manure", "khad"])
        is_help = any(word in query_lower for word in ["help", "what can you do", "features", "how can you help", "what do you do", "guide", "assist", "options", "menu", "commands"])

        if is_help:
            advice = (
                f"Namaste {context['farmer_name']}! I'm AgriSarathi, your AI farming assistant. Here's what I can do for you:\n\n"
                "🌾 **Crop Advice** — Ask me about pest control, diseases, fertilizers, irrigation, and crop management.\n"
                "📸 **AI Crop Doctor** — Take a photo of your crop and I'll diagnose diseases and suggest treatments.\n"
                "🌤️ **Weather Forecast** — Get real-time weather for your location with farm risk analysis.\n"
                "📊 **Market Prices** — Check latest mandi prices for crops near your area.\n"
                "🧮 **Farm Calculator** — Calculate seed, fertilizer, and input costs.\n"
                "📅 **Task Planner** — Set farming reminders and manage your calendar.\n"
                "🏛️ **Government Schemes** — Browse latest agricultural schemes and subsidies.\n"
                "🔧 **Machinery Info** — Find equipment rental and usage information.\n"
                "🎤 **Voice Commands** — Just tap the mic and speak in your language!\n\n"
                "Try asking: 'My tomato leaves are curling' or 'What is the price of wheat today?'"
            )
            return {
                "id": f"adv_{datetime.now().strftime('%Y%m%d%H%M%S')}",
                "advice": advice,
                "confidence": 1.0,
                "reasoning": "User asked for help — listing all app features.",
                "urgency": "Low",
                "timestamp": datetime.now().isoformat()
            }

        if is_pest and "tomato" in query_lower:
            advice = f"Namaste {context['farmer_name']}. Based on the curling leaves in your tomato crop in {context['location']}, it is likely a Thrips infestation. ACTION: Spray Neem Oil (5ml/L) immediately."
            confidence = 0.85
            reasoning = "Curling leaves + Summer = High Thrips probability."
        elif is_pest:
            advice = f"Hello {context['farmer_name']}. For pest issues in {context['location']}, inspect your crop closely. ACTION: Use Neem Oil (5ml/L) as a first step and consult your local KVK for specifics."
            confidence = 0.75
            reasoning = "Pest symptoms detected, general advisory."
        elif is_fertilizer:
            advice = f"For better growth of your crops in {context['location']}, apply balanced NPK. A top dressing of Urea (25kg/acre) followed by light irrigation is recommended."
            confidence = 0.80
            reasoning = "Standard growth recommendation."
        elif is_irrigation:
            advice = f"{context['farmer_name']}, check your soil moisture levels. Since the weather is {context['weather']}, adjust irrigation accordingly. Avoid over-watering."
            confidence = 0.85
            reasoning = "Irrigation guidance based on weather context."
        else:
            advice = f"I've analyzed your query about '{query}'. Please mention specific crop name and symptoms for more detailed advice. Visit your local KVK for personalized guidance."
            confidence = 0.70
            reasoning = "General guidance — no specific crop/pest identified."

        return {
            "id": f"adv_{datetime.now().strftime('%Y%m%d%H%M%S')}",
            "advice": advice,
            "confidence": confidence,
            "reasoning": reasoning,
            "urgency": "High" if is_pest else "Medium",
            "timestamp": datetime.now().isoformat()
        }


def generate_advice(query_text: str, context: dict) -> Dict[str, Any]:
    """Sync wrapper for the async engine."""
    import asyncio
    return asyncio.run(AdvisoryReasoningEngine.get_actionable_advice(query_text, context))
